# Generated by Django 4.1.1 on 2022-10-11 18:06

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photos_name_videos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='poster',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_webm',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
