# Generated by Django 4.1.1 on 2022-10-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_videos_poster_videos_video_webm'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
